# docker-compose.yml
version: '3.8'

services:

  backend_full:
    build:
      context: ./backend_full
    environment:
      DATABASE_URL: postgresql+psycopg2://cavina:cavina@db:5432/cavina
      JWT_SECRET_KEY: changeme
      SWAGGER_ENABLED: "true"
      STRUCTLOG_JSON: "false"
    depends_on:
      - db
    ports:
      - "8001:8000"

  db:
    image: postgres:18
    environment:
      POSTGRES_USER: cavina
      POSTGRES_PASSWORD: cavina
      POSTGRES_DB: cavina
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./data:/docker-entrypoint-initdb.d:rw

  db_simple:
    image: postgres:18
    environment:
      POSTGRES_DB: product_catalog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "55444:5432"
    volumes:
      - pgdata_simple:/var/lib/postgresql
  #
  #backend_simple:
  #  build:
  #    context: ./backend_simple
  #    dockerfile: Dockerfile
  #  ports:
  #    - "8022:8000"
  #  depends_on:
  #    - db_simple
  #  environment:
  #    - DATABASE_URL=postgresql://user:password@db_simple:5432/product_catalog
  #  command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8088:4000"
    depends_on:
      - backend_full

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    depends_on:
      - backend_full

volumes:
  pgdata:
  pgdata_simple: