services:

  backend_full:
    build:
      context: ./backend_full
    environment:
      DATABASE_URL: postgresql+psycopg2://cavina:cavina@db:5432/cavina
      JWT_SECRET_KEY: changeme
      SWAGGER_ENABLED: "true"
      STRUCTLOG_JSON: "false"
    depends_on:
      - db
    ports:
      - "8001:8000"
    volumes:
      - ./data:/app/data:rw
    env_file:
      - .env

  db:
    image: postgres:18
    environment:
      POSTGRES_USER: cavina
      POSTGRES_PASSWORD: cavina
      POSTGRES_DB: cavina
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./data:/docker-entrypoint-initdb.d:rw

  db_simple:
    image: postgres:18
    environment:
      POSTGRES_DB: product_catalog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "55444:5432"
    volumes:
      - pgdata_simple:/var/lib/postgresql
  #

  #frontend:
  #  build:
  #    context: ./frontend
  #    dockerfile: Dockerfile.dev
  #  ports:
  #    - "8088:4000"
  #  depends_on:
  #    - backend_full

  #front:
  #  build:
  #    context: ./front
  #    dockerfile: Dockerfile
  #  ports:
  #    - "8090:80"
  #  depends_on:
  #    - backend_full

  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    ports:
      - "8090:5173"
    volumes:
      - ./front:/app
      - ./data/product_images:/app/public/images:r
      - /app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  pgdata:
  pgdata_simple: